name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '🚦 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'build'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🔄 Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '🎨 Code Style'
    labels:
      - 'style'
      - 'formatting'
change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'chore'
      - 'maintenance'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for their contributions!
