services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-pku}
      POSTGRES_USER: ${DB_USER:-pku}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pku}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-pku} -d ${DB_NAME:-pku}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./services/api
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/pku?characterEncoding=UTF-8&useUnicode=true}
      DB_USER: ${DB_USER:-pku}
      DB_PASSWORD: ${DB_PASSWORD:-pku}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db_data: