spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pku}
    username: ${DB_USER:pku}
    password: ${DB_PASSWORD:pku}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
