version: '3.8'
services:
  ui:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080
