name: ci

on:
  push: { branches: [ main, develop ] }
  pull_request: { branches: [ main, develop ] }

permissions: { contents: read }
concurrency: { group: ci-${{ github.ref }}, cancel-in-progress: true }

jobs:
  build-test:
    runs-on: ubuntu-latest

    # Testcontainers-ს Docker სჭირდება; ubuntu-latest-ზე უკვე გაქვს docker daemon.
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    defaults:
      run:
        working-directory: services/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Docker info (debug)
        run: docker info

      - name: Build & Test (unit + integration via Testcontainers)
        run: mvn -B -ntp verify

      - name: Upload test & DC reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
            target/dependency-check/**
