name: ci

on:
  push: { branches: [ main, develop ] }
  pull_request: { branches: [ main, develop ] }

permissions: { contents: read }
concurrency: { group: ci-${{ github.ref }}, cancel-in-progress: true }

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: pku
          POSTGRES_USER: pku
          POSTGRES_PASSWORD: pku
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U pku -d pku"
          --health-interval=5s --health-timeout=3s --health-retries=25

    defaults:
      run:
        working-directory: services/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Print env
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          psql --version || true

      - name: Run tests (unit + IT)
        env:
          SPRING_PROFILES_ACTIVE: test
          # ტესტებისთვის JWT/Secrets დეფოლტები
          SPRING_SECURITY_JWT_SECRET: "dummy-test-secret"
          # DB (localhost, რადგან პორტი გამოშვებულია)
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/pku
          SPRING_DATASOURCE_USERNAME: pku
          SPRING_DATASOURCE_PASSWORD: pku
        run: mvn -B -ntp -fae verify

      # ჩავაგდოთ რეპორტები, თუ რამე გაწითლდება
      - name: Upload surefire/failsafe reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            services/api/target/surefire-reports/**
            services/api/target/failsafe-reports/**