name: CI - Build, Test & Quality

on:
  push: 
    branches: [ main, develop ]
  pull_request: 
    branches: [ main, develop ]
  workflow_dispatch:  # Enable manual triggering

permissions: 
  contents: read
  checks: write

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: services/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Spotless Check (Google Java Format)
        run: mvn -B spotless:check
        continue-on-error: false

      - name: Maven Enforcer (Dependency Convergence)
        run: mvn -B enforcer:enforce@enforce-versions

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: code-quality

    defaults:
      run:
        working-directory: services/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify Docker
        run: docker info

      - name: Cache OWASP DC data
        uses: actions/cache@v4
        with:
          path: services/api/target/dependency-check
          key: ${{ runner.os }}-dc-${{ hashFiles('services/api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dc-

      - name: OWASP Dependency Check
        continue-on-error: true
        run: mvn -B -ntp -DskipTests org.owasp:dependency-check-maven:12.1.0:check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Build & Unit Tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: >
          mvn -B -ntp clean test
          -Djunit.jupiter.exclude.tags=it
          -DskipDockerTests=true
          -Dsurefire.printSummary=true

      - name: Integration Tests (Testcontainers)
        run: mvn -B -ntp verify -DskipTests=false -Djunit.jupiter.include.tags=it -DskipDockerTests=false
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Generate JaCoCo Coverage Report
        run: mvn -B jacoco:report

      - name: Check Coverage Thresholds
        run: mvn -B jacoco:check
        continue-on-error: true

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            services/api/target/surefire-reports/**
            services/api/target/failsafe-reports/**
            services/api/target/site/jacoco/**
          retention-days: 7

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: services/api/target/surefire-reports/*.xml,services/api/target/failsafe-reports/*.xml
          reporter: java-junit
          fail-on-error: false
