name: java-ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: pku
          POSTGRES_USER: pku
          POSTGRES_PASSWORD: pku
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U pku -d pku"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build & Test
        run: |
          cd services/api
          mvn -B -ntp -DskipTests=false verify
