name: Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC
  push:
    branches: [ main ]
    paths:
      - 'services/api/pom.xml'
      - '.github/workflows/security-scan.yml'

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: services/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -B clean verify -Psecurity-scan
        continue-on-error: true

      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            services/api/target/dependency-check-report.html
            services/api/target/dependency-check-report.json
          retention-days: 30

      - name: Check for High/Critical Vulnerabilities
        if: always()
        run: |
          if [ -f target/dependency-check-report.json ]; then
            HIGH_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="HIGH")] | length' target/dependency-check-report.json)
            CRITICAL_COUNT=$(jq '[.dependencies[]?.vulnerabilities[]? | select(.severity=="CRITICAL")] | length' target/dependency-check-report.json)
            echo "High vulnerabilities: $HIGH_COUNT"
            echo "Critical vulnerabilities: $CRITICAL_COUNT"
            if [ "$CRITICAL_COUNT" -gt "0" ]; then
              echo "::error::Found $CRITICAL_COUNT critical vulnerabilities!"
              exit 1
            fi
          fi

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (filesystem)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'services/api'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'


